### ISSUE TITLE
Quetion 1

### ISSUE THREAD

**Issue by ziandzivan** [CaptainThrowback/android_device_htc_ime#1]
i have many different question from my domestic forum, stupid and useful. One of them why TWRP patches both slots, active and non-active at rerm-twrp ? 
The problems is that it is broken OTA workings. There is a method to return to stock for receiving OTA updates using an active clean slot and it is without Untouched backup !
Could you please explain why the TWRP patched both slots ? Just it is only easy to have results ?
P.S. I do not think that  you need a log in this case.

**Comment by CaptainThrowback** [comment]
This is not an issue with TWRP. If you have general questions about TWRP, you should join Slack and ask them there. The Issues tab here is for bugs with the unofficial builds, not general TWRP questions.

**Comment by ziandzivan** [comment]
Really ?
It was easy to check what slot is active and your TWRP is knows about it..
We need to use a script to issue  your twrp.

**Comment by ziandzivan** [comment]
[twrp-installer-ime_active_slot_signed.zip](https://github.com/CaptainThrowback/android_device_htc_ime/files/4498757/twrp-installer-ime_active_slot_signed.zip)
